cmake_minimum_required(VERSION 3.4...3.31)
set(WASI TRUE)
set(CMAKE_SYSTEM_NAME WASI)
set(CMAKE_SYSTEM_VERSION 1)
set(CMAKE_SYSTEM_PROCESSOR wasm32)
set(CMAKE_C_COMPILER /home/sc/wasi-sdk-34.0-x86_64-linux/bin/clang)
set(CMAKE_CXX_COMPILER /home/sc/wasi-sdk-34.0-x86_64-linux/bin/clang++)
set(CMAKE_LINKER /home/sc/wasi-sdk-34.0-x86_64-linux/bin/wasm-ld CACHE STRING "wasi build")
set(CMAKE_AR /home/sc/wasi-sdk-34.0-x86_64-linux/bin/ar CACHE STRING "wasi build")
set(CMAKE_RANLIB /home/sc/wasi-sdk-34.0-x86_64-linux/bin/ranlib CACHE STRING "wasi build")
set(CMAKE_C_COMPILER_TARGET wasm32-wasip1)
set(CMAKE_CXX_COMPILER_TARGET wasm32-wasip1)
set(CMAKE_C_FLAGS "--sysroot /home/sc/wasi-sdk-34.0-x86_64-linux/share/wasi-sysroot -Wno-error -Wno-deprecated-builtins -D_WASI_EMULATED_MMAN -DGLOB_TILDE=0" CACHE STRING "wasi build")
set(CMAKE_CXX_FLAGS "--sysroot /home/sc/wasi-sdk-34.0-x86_64-linux/share/wasi-sysroot -Wno-error -Wno-deprecated-builtins -D_WASI_EMULATED_MMAN -DGLOB_TILDE=0" CACHE STRING "wasi build")
set(CMAKE_EXE_LINKER_FLAGS "-Wl,--strip-all" CACHE STRING "wasi build")
# After the objects that reference them -- see the nextpnr script.
set(CMAKE_CXX_STANDARD_LIBRARIES "/mnt/i/Hotwright/0-xilinx-bits/wasm-build/wasi_throw_stubs.o -lwasi-emulated-mman" CACHE STRING "wasi build")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
